#!/bin/bash

volume=$3
server=$1
pool=$2
frequency="yearly"

lastsnap=$(zfs holds `zfs list $pool/$volume -t snapshot -o name -s creation` 2>/dev/null | grep backup-rclone-$frequency | awk '{printf $1}' | tail -n 1)
snapname=$(zfs list -t snapshot $pool/$volume -o name -s creation | tail -n1)

zfs hold backup-rclone-$frequency $snapname
zfs send -c -w -v $snapname 2>/root/zfssend-$volume.log | rclone --config=/etc/rclone.conf --log-file=/root/rclonezfs-$volume.log rcat server-backup-crypt:zfs/$server/$pool/$volume/$snapname-$frequency

if [ $? == 0 ]; then
  if [ $lastsnap ];then
   zfs list $pool/$volume -t snapshot -o name -S creation 2>/dev/null | grep backup-rclone-monthly | awk '{printf $1}'` | xargs zfs release backup-rclone-monthly
   zfs list $pool/$volume -t snapshot -o name -S creation 2>/dev/null | grep -v backup-rclone-daily | awk '{printf $1}'` | xargs zfs release backup-rclone-daily
   zfs list $pool/$volume -t snapshot -o name -S creation 2>/dev/null | grep backup-rclone-yearly | tail -n 2 | head -n 1 | awk '{printf $1}'` | xargs zfs release backup-rclone-yearly
  fi
fi
